# Generated by Django 3.1.6 on 2021-10-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_input', models.ImageField(null=True, upload_to='photo_input', verbose_name='Photo')),
                ('session', models.CharField(max_length=50, null=True, verbose_name='Session Key')),
                ('action', models.CharField(blank=True, max_length=50, null=True, verbose_name='Action')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
